version: '3.2'

services:
  service1:
    image: asinatra/secure
    container_name: service1
  service2:
    image: asinatra/secure
    container_name: service2
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    image: asinatra/ngnix
    container_name: nginx
    ports:
     - "80:80"
   